POST http://localhost:8000/contacts/create/
Content-Type: application/json

{
  "lastname": "Chouia",
  "firstname": "Abderrahman"
}
######################

GET http://localhost:8000/contacts/

##########################"
POST http://localhost:8000/deals/create/
Content-Type: application/json

{
  "deal_name": "Deal - Chouia Abderrahman"
}

################################

POST http://localhost:8000/deals/associate/
Content-Type: application/json

{
  "contact_id": "32109216466",
  "deal_id": "16473007324"
}

################################
GET http://localhost:8000/contacts/
